package mapper

import (
	"fmt"
	"strings"
)

// GenerateConsts produces a Go const block for internal/pattern/offsets.go.
// Pass -1 for any value that is not yet known; those lines show 0x???? as a placeholder.
func GenerateConsts(beatDataOffset, trackStride, stepStride int) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by beat-mapper session — verify before use\n")
	sb.WriteString("const (\n")
	writeConst(&sb, "BeatDataOffset", beatDataOffset, "start of beat section in unescaped project payload")
	writeConst(&sb, "TrackStride", trackStride, "bytes per track")
	writeConst(&sb, "StepStride", stepStride, "bytes per step (gate + velocity)")
	sb.WriteString("\tStepGateByte     = 0       // offset within step: gate flag\n")
	sb.WriteString("\tStepVelocityByte = 1       // offset within step: velocity\n")
	sb.WriteString(")\n")
	return sb.String()
}

func writeConst(sb *strings.Builder, name string, val int, comment string) {
	if val < 0 {
		fmt.Fprintf(sb, "\t%-20s = 0x????  // %s — not yet determined\n", name, comment)
	} else {
		fmt.Fprintf(sb, "\t%-20s = 0x%04X  // %s\n", name, val, comment)
	}
}
